"""init schema

Revision ID: a51ef181a13d
Revises: 
Create Date: 2025-12-30 23:24:04.012173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a51ef181a13d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permiso_user_tabla')
    op.drop_index('idx_inscripcion_equipo', table_name='inscripcion_torneo')
    op.drop_index('idx_inscripcion_torneo', table_name='inscripcion_torneo')
    op.drop_table('inscripcion_torneo')
    op.drop_table('fixture_fecha')
    op.drop_index('idx_auditoria_operacion', table_name='auditoria_log')
    op.drop_index('idx_auditoria_tabla_fecha', table_name='auditoria_log')
    op.drop_index('idx_auditoria_usuario', table_name='auditoria_log')
    op.drop_table('auditoria_log')
    op.drop_table('fixture_partido')
    op.alter_column('club', 'id_club',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('club', 'provincia',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('club', 'ciudad',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint('club_unq_nombre_ciudad', 'club', type_='unique')
    op.drop_column('club', 'actualizado_por')
    op.drop_column('club', 'actualizado_en')
    op.drop_column('club', 'creado_por')
    op.drop_column('club', 'creado_en')
    op.alter_column('equipo', 'id_equipo',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('equipo', 'creado_en',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('equipo', 'actualizado_en',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('equipo_unq_club_categoria', 'equipo', type_='unique')
    op.drop_index('idx_equipo_club', table_name='equipo')
    op.drop_constraint('equipo_id_club_fkey', 'equipo', type_='foreignkey')
    op.create_foreign_key(None, 'equipo', 'club', ['id_club'], ['id_club'], ondelete='CASCADE')
    op.add_column('fase', sa.Column('torneo_id', sa.Integer(), nullable=False))
    op.alter_column('fase', 'id_fase',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('fase', 'tipo',
               existing_type=postgresql.ENUM('liga', 'eliminacion', 'grupos', name='tipo_fase_enum'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_constraint('fase_id_torneo_fkey', 'fase', type_='foreignkey')
    op.create_foreign_key(None, 'fase', 'torneo', ['torneo_id'], ['id_torneo'], ondelete='CASCADE')
    op.drop_column('fase', 'actualizado_en')
    op.drop_column('fase', 'creado_por')
    op.drop_column('fase', 'creado_en')
    op.drop_column('fase', 'id_torneo')
    op.drop_column('fase', 'actualizado_por')
    op.alter_column('gol', 'id_gol',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('gol', 'referencia_gol',
               existing_type=postgresql.ENUM('GJ', 'GC', 'GP', 'DP', name='referencia_gol_enum'),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('idx_gol_jugador', table_name='gol')
    op.drop_index('idx_gol_partido', table_name='gol')
    op.drop_constraint('gol_id_partido_fkey', 'gol', type_='foreignkey')
    op.drop_constraint('gol_id_participante_partido_fkey', 'gol', type_='foreignkey')
    op.create_foreign_key(None, 'gol', 'partido', ['id_partido'], ['id_partido'], ondelete='CASCADE')
    op.create_foreign_key(None, 'gol', 'participan_partido', ['id_participante_partido'], ['id_participante_partido'])
    op.drop_column('gol', 'actualizado_en')
    op.drop_column('gol', 'creado_por')
    op.drop_column('gol', 'motivo_anulacion')
    op.drop_column('gol', 'anulado_en')
    op.drop_column('gol', 'creado_en')
    op.drop_column('gol', 'anulado_por')
    op.drop_column('gol', 'actualizado_por')
    op.drop_column('gol', 'anulado')
    op.add_column('participan_partido', sa.Column('id_plantel', sa.Integer(), nullable=False))
    op.alter_column('participan_partido', 'id_participante_partido',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('participan_partido', 'numero_camiseta',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('idx_participacion_partido', table_name='participan_partido')
    op.drop_index('idx_participante_integrante', table_name='participan_partido')
    op.drop_constraint('unq_jugador_partido', 'participan_partido', type_='unique')
    op.drop_constraint('participan_partido_id_plantel_integrante_fkey', 'participan_partido', type_='foreignkey')
    op.create_foreign_key(None, 'participan_partido', 'plantel', ['id_plantel'], ['id_plantel'])
    op.drop_column('participan_partido', 'actualizado_en')
    op.drop_column('participan_partido', 'creado_por')
    op.drop_column('participan_partido', 'id_plantel_integrante')
    op.drop_column('participan_partido', 'creado_en')
    op.drop_column('participan_partido', 'actualizado_por')
    op.add_column('partido', sa.Column('capitan_local', sa.Integer(), nullable=True))
    op.add_column('partido', sa.Column('capitan_visitante', sa.Integer(), nullable=True))
    op.alter_column('partido', 'id_partido',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('partido', 'horario',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('partido', 'tipo_fase',
               existing_type=postgresql.ENUM('liga', 'eliminacion', 'grupos', name='tipo_fase_enum'),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'liga'::tipo_fase_enum"))
    op.drop_index('idx_actualizado_en_partido', table_name='partido')
    op.drop_index('idx_confirmado_en_partido', table_name='partido')
    op.drop_index('idx_creado_en_partido', table_name='partido')
    op.drop_index('idx_creado_por_partido', table_name='partido')
    op.drop_index('idx_partido_fecha_horario', table_name='partido')
    op.drop_index('idx_partido_local', table_name='partido')
    op.drop_index('idx_partido_torneo_fecha', table_name='partido')
    op.drop_index('idx_partido_visitante', table_name='partido')
    op.drop_constraint('partido_unq_equipo_fecha_horario', 'partido', type_='unique')
    op.drop_constraint('partido_id_capitan_local_fkey', 'partido', type_='foreignkey')
    op.drop_constraint('partido_id_capitan_visitante_fkey', 'partido', type_='foreignkey')
    op.create_foreign_key(None, 'partido', 'participan_partido', ['capitan_local'], ['id_participante_partido'])
    op.create_foreign_key(None, 'partido', 'participan_partido', ['capitan_visitante'], ['id_participante_partido'])
    op.drop_column('partido', 'confirmado_por')
    op.drop_column('partido', 'actualizado_en')
    op.drop_column('partido', 'creado_por')
    op.drop_column('partido', 'actualizado_por')
    op.drop_column('partido', 'id_capitan_local')
    op.drop_column('partido', 'creado_en')
    op.drop_column('partido', 'confirmado_en')
    op.drop_column('partido', 'id_capitan_visitante')
    op.alter_column('persona', 'id_persona',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('persona', 'genero',
               existing_type=postgresql.ENUM('Masculino', 'Femenino', name='genero_persona_tipo'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_index('idx_persona_dni', table_name='persona')
    op.drop_index('idx_persona_nombre_apellido', table_name='persona')
    op.drop_column('persona', 'actualizado_por')
    op.drop_column('persona', 'actualizado_en')
    op.drop_column('persona', 'creado_por')
    op.drop_column('persona', 'creado_en')
    op.alter_column('persona_rol', 'id_persona_rol',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('persona_rol', 'rol',
               existing_type=postgresql.ENUM('jugador', 'entrenador', 'arbitro', name='rol_persona_tipo'),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.drop_index('idx_persona_rol_activo', table_name='persona_rol', postgresql_where='(fecha_hasta IS NULL)')
    op.drop_index('idx_persona_rol_persona', table_name='persona_rol')
    op.drop_index('idx_persona_rol_rol', table_name='persona_rol')
    op.drop_index('unq_persona_rol_activo', table_name='persona_rol', postgresql_where='(fecha_hasta IS NULL)')
    op.drop_constraint('persona_rol_id_persona_fkey', 'persona_rol', type_='foreignkey')
    op.create_foreign_key(None, 'persona_rol', 'persona', ['id_persona'], ['id_persona'], ondelete='CASCADE')
    op.drop_column('persona_rol', 'actualizado_por')
    op.drop_column('persona_rol', 'actualizado_en')
    op.drop_column('persona_rol', 'creado_por')
    op.drop_column('persona_rol', 'creado_en')
    op.alter_column('plantel', 'id_plantel',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('plantel', 'fecha_creacion',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.drop_index('idx_plantel_equipo', table_name='plantel')
    op.drop_constraint('plantel_id_equipo_id_torneo_key', 'plantel', type_='unique')
    op.drop_constraint('plantel_id_equipo_fkey', 'plantel', type_='foreignkey')
    op.create_foreign_key(None, 'plantel', 'equipo', ['id_equipo'], ['id_equipo'])
    op.drop_column('plantel', 'actualizado_por')
    op.drop_column('plantel', 'actualizado_en')
    op.drop_column('plantel', 'creado_por')
    op.drop_column('plantel', 'creado_en')
    op.alter_column('plantel_integrante', 'id_plantel_integrante',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('plantel_integrante', 'rol_en_plantel',
               existing_type=postgresql.ENUM('jugador', 'entrenador', name='rol_plantel_tipo'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_index('idx_pi_fecha_baja', table_name='plantel_integrante')
    op.drop_index('idx_pi_persona', table_name='plantel_integrante')
    op.drop_index('idx_pi_plantel', table_name='plantel_integrante')
    op.drop_index('idx_pi_rol', table_name='plantel_integrante')
    op.drop_index('idx_plantel_integrante_plantel_rol', table_name='plantel_integrante')
    op.drop_constraint('unq_plantel_persona_rol', 'plantel_integrante', type_='unique')
    op.drop_constraint('plantel_integrante_id_plantel_fkey', 'plantel_integrante', type_='foreignkey')
    op.create_foreign_key(None, 'plantel_integrante', 'plantel', ['id_plantel'], ['id_plantel'])
    op.drop_column('plantel_integrante', 'actualizado_por')
    op.drop_column('plantel_integrante', 'actualizado_en')
    op.drop_column('plantel_integrante', 'creado_por')
    op.drop_column('plantel_integrante', 'creado_en')
    op.add_column('posicion', sa.Column('fecha_actualizacion', sa.String(), nullable=True))
    op.alter_column('posicion', 'id_posicion',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('idx_posicion_torneo', table_name='posicion')
    op.drop_constraint('posicion_equipo_torneo_unq', 'posicion', type_='unique')
    op.drop_column('posicion', 'actualizado_por')
    op.drop_column('posicion', 'actualizado_en')
    op.drop_column('posicion', 'creado_por')
    op.drop_column('posicion', 'creado_en')
    op.alter_column('refresh_token', 'id_refresh_token',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('refresh_token', 'token_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('refresh_token', 'user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('idx_refresh_token_activo', table_name='refresh_token')
    op.drop_index('idx_refresh_usuario', table_name='refresh_token')
    op.create_index(op.f('ix_refresh_token_id_refresh_token'), 'refresh_token', ['id_refresh_token'], unique=False)
    op.add_column('suspension', sa.Column('id_persona_rol', sa.Integer(), nullable=False))
    op.add_column('suspension', sa.Column('cantidad_partidos', sa.Integer(), nullable=False))
    op.add_column('suspension', sa.Column('fecha_inicio', sa.String(), nullable=True))
    op.add_column('suspension', sa.Column('fecha_fin', sa.String(), nullable=True))
    op.add_column('suspension', sa.Column('fecha_actualizacion', sa.String(), nullable=True))
    op.add_column('suspension', sa.Column('estado', sa.String(), nullable=True))
    op.alter_column('suspension', 'id_suspension',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('suspension', 'motivo',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_index('idx_susp_activa_fecha', table_name='suspension')
    op.drop_index('idx_susp_fin', table_name='suspension')
    op.drop_index('idx_susp_persona', table_name='suspension')
    op.drop_index('idx_susp_persona_activa', table_name='suspension', postgresql_where='(activa = true)')
    op.drop_index('idx_susp_torneo', table_name='suspension')
    op.drop_constraint('suspension_id_persona_fkey', 'suspension', type_='foreignkey')
    op.drop_constraint('suspension_id_partido_origen_fkey', 'suspension', type_='foreignkey')
    op.drop_constraint('suspension_id_torneo_fkey', 'suspension', type_='foreignkey')
    op.create_foreign_key(None, 'suspension', 'persona_rol', ['id_persona_rol'], ['id_persona_rol'])
    op.drop_column('suspension', 'id_persona')
    op.drop_column('suspension', 'tipo_suspension')
    op.drop_column('suspension', 'actualizado_en')
    op.drop_column('suspension', 'id_partido_origen')
    op.drop_column('suspension', 'cumplidas')
    op.drop_column('suspension', 'creado_por')
    op.drop_column('suspension', 'activa')
    op.drop_column('suspension', 'fecha_fin_suspension')
    op.drop_column('suspension', 'creado_en')
    op.drop_column('suspension', 'fechas_suspension')
    op.drop_column('suspension', 'id_torneo')
    op.drop_column('suspension', 'actualizado_por')
    op.alter_column('tarjeta', 'id_tarjeta',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('tarjeta', 'tipo',
               existing_type=postgresql.ENUM('verde', 'amarilla', 'roja', name='tipo_tarjeta_enum'),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('idx_tarjeta_partido', table_name='tarjeta')
    op.drop_column('tarjeta', 'revisada')
    op.drop_column('tarjeta', 'actualizado_en')
    op.drop_column('tarjeta', 'creado_por')
    op.drop_column('tarjeta', 'decision_revision')
    op.drop_column('tarjeta', 'revisada_en')
    op.drop_column('tarjeta', 'creado_en')
    op.drop_column('tarjeta', 'actualizado_por')
    op.drop_column('tarjeta', 'revisada_por')
    op.alter_column('torneo', 'id_torneo',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('torneo', 'categoria',
               existing_type=postgresql.ENUM('A', 'B', 'Sub 19', 'Sub 16', 'Sub 14', 'Sub 12', name='categoria_tipo'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('torneo', 'genero',
               existing_type=postgresql.ENUM('Masculino', 'Femenino', 'Mixto', name='genero_competencia_tipo'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_constraint('torneo_nombre_cat', 'torneo', type_='unique')
    op.drop_column('torneo', 'actualizado_por')
    op.drop_column('torneo', 'actualizado_en')
    op.drop_column('torneo', 'creado_por')
    op.drop_column('torneo', 'creado_en')
    op.alter_column('usuario', 'id_usuario',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('usuario', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('usuario', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('usuario', 'rol',
               existing_type=postgresql.ENUM('superusuario', 'admin', 'editor', 'lector', name='usuario_tipo'),
               type_=postgresql.ENUM('superusuario', 'admin', 'editor', 'lector', name='rol_usuario_tipo'),
               existing_nullable=False,
               existing_server_default=sa.text("'lector'::usuario_tipo"))
    op.drop_index('idx_usuario_activo', table_name='usuario')
    op.drop_index('idx_usuario_persona', table_name='usuario')
    op.drop_index('idx_usuario_rol', table_name='usuario')
    op.create_index(op.f('ix_usuario_id_usuario'), 'usuario', ['id_usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_id_usuario'), table_name='usuario')
    op.create_index('idx_usuario_rol', 'usuario', ['rol'], unique=False)
    op.create_index('idx_usuario_persona', 'usuario', ['id_persona'], unique=False)
    op.create_index('idx_usuario_activo', 'usuario', ['activo'], unique=False)
    op.alter_column('usuario', 'rol',
               existing_type=postgresql.ENUM('superusuario', 'admin', 'editor', 'lector', name='rol_usuario_tipo'),
               type_=postgresql.ENUM('superusuario', 'admin', 'editor', 'lector', name='usuario_tipo'),
               existing_nullable=False,
               existing_server_default=sa.text("'lector'::usuario_tipo"))
    op.alter_column('usuario', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('usuario', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('usuario', 'id_usuario',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('torneo', sa.Column('creado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('torneo', sa.Column('creado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('torneo', sa.Column('actualizado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('torneo', sa.Column('actualizado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint('torneo_nombre_cat', 'torneo', ['nombre', 'categoria'])
    op.alter_column('torneo', 'genero',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('Masculino', 'Femenino', 'Mixto', name='genero_competencia_tipo'),
               existing_nullable=False)
    op.alter_column('torneo', 'categoria',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('A', 'B', 'Sub 19', 'Sub 16', 'Sub 14', 'Sub 12', name='categoria_tipo'),
               existing_nullable=False)
    op.alter_column('torneo', 'id_torneo',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('tarjeta', sa.Column('revisada_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tarjeta', sa.Column('actualizado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tarjeta', sa.Column('creado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('tarjeta', sa.Column('revisada_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tarjeta', sa.Column('decision_revision', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('tarjeta', sa.Column('creado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tarjeta', sa.Column('actualizado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('tarjeta', sa.Column('revisada', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.create_index('idx_tarjeta_partido', 'tarjeta', ['id_partido'], unique=False)
    op.alter_column('tarjeta', 'tipo',
               existing_type=sa.String(),
               type_=postgresql.ENUM('verde', 'amarilla', 'roja', name='tipo_tarjeta_enum'),
               existing_nullable=False)
    op.alter_column('tarjeta', 'id_tarjeta',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('suspension', sa.Column('actualizado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('suspension', sa.Column('id_torneo', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('suspension', sa.Column('fechas_suspension', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('suspension', sa.Column('creado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('suspension', sa.Column('fecha_fin_suspension', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('suspension', sa.Column('activa', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('suspension', sa.Column('creado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('suspension', sa.Column('cumplidas', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('suspension', sa.Column('id_partido_origen', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('suspension', sa.Column('actualizado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('suspension', sa.Column('tipo_suspension', postgresql.ENUM('por_partidos', 'por_fecha', name='tipo_suspension_enum'), autoincrement=False, nullable=False))
    op.add_column('suspension', sa.Column('id_persona', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'suspension', type_='foreignkey')
    op.create_foreign_key('suspension_id_torneo_fkey', 'suspension', 'torneo', ['id_torneo'], ['id_torneo'])
    op.create_foreign_key('suspension_id_partido_origen_fkey', 'suspension', 'partido', ['id_partido_origen'], ['id_partido'])
    op.create_foreign_key('suspension_id_persona_fkey', 'suspension', 'persona', ['id_persona'], ['id_persona'])
    op.create_index('idx_susp_torneo', 'suspension', ['id_torneo'], unique=False)
    op.create_index('idx_susp_persona_activa', 'suspension', ['id_persona'], unique=False, postgresql_where='(activa = true)')
    op.create_index('idx_susp_persona', 'suspension', ['id_persona'], unique=False)
    op.create_index('idx_susp_fin', 'suspension', ['fecha_fin_suspension'], unique=False)
    op.create_index('idx_susp_activa_fecha', 'suspension', ['activa', 'fecha_fin_suspension'], unique=False)
    op.alter_column('suspension', 'motivo',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('suspension', 'id_suspension',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('suspension', 'estado')
    op.drop_column('suspension', 'fecha_actualizacion')
    op.drop_column('suspension', 'fecha_fin')
    op.drop_column('suspension', 'fecha_inicio')
    op.drop_column('suspension', 'cantidad_partidos')
    op.drop_column('suspension', 'id_persona_rol')
    op.drop_index(op.f('ix_refresh_token_id_refresh_token'), table_name='refresh_token')
    op.create_index('idx_refresh_usuario', 'refresh_token', ['id_usuario'], unique=False)
    op.create_index('idx_refresh_token_activo', 'refresh_token', ['revoked', 'expires_at'], unique=False)
    op.alter_column('refresh_token', 'user_agent',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('refresh_token', 'token_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('refresh_token', 'id_refresh_token',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('posicion', sa.Column('creado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('posicion', sa.Column('creado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('posicion', sa.Column('actualizado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('posicion', sa.Column('actualizado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint('posicion_equipo_torneo_unq', 'posicion', ['id_torneo', 'id_equipo'])
    op.create_index('idx_posicion_torneo', 'posicion', ['id_torneo'], unique=False)
    op.alter_column('posicion', 'id_posicion',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('posicion', 'fecha_actualizacion')
    op.add_column('plantel_integrante', sa.Column('creado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('plantel_integrante', sa.Column('creado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('plantel_integrante', sa.Column('actualizado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('plantel_integrante', sa.Column('actualizado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'plantel_integrante', type_='foreignkey')
    op.create_foreign_key('plantel_integrante_id_plantel_fkey', 'plantel_integrante', 'plantel', ['id_plantel'], ['id_plantel'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_unique_constraint('unq_plantel_persona_rol', 'plantel_integrante', ['id_plantel', 'id_persona', 'rol_en_plantel'])
    op.create_index('idx_plantel_integrante_plantel_rol', 'plantel_integrante', ['id_plantel', 'rol_en_plantel', 'fecha_baja'], unique=False)
    op.create_index('idx_pi_rol', 'plantel_integrante', ['rol_en_plantel'], unique=False)
    op.create_index('idx_pi_plantel', 'plantel_integrante', ['id_plantel'], unique=False)
    op.create_index('idx_pi_persona', 'plantel_integrante', ['id_persona'], unique=False)
    op.create_index('idx_pi_fecha_baja', 'plantel_integrante', ['fecha_baja'], unique=False)
    op.alter_column('plantel_integrante', 'rol_en_plantel',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('jugador', 'entrenador', name='rol_plantel_tipo'),
               existing_nullable=False)
    op.alter_column('plantel_integrante', 'id_plantel_integrante',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('plantel', sa.Column('creado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('plantel', sa.Column('creado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('plantel', sa.Column('actualizado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('plantel', sa.Column('actualizado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'plantel', type_='foreignkey')
    op.create_foreign_key('plantel_id_equipo_fkey', 'plantel', 'equipo', ['id_equipo'], ['id_equipo'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_unique_constraint('plantel_id_equipo_id_torneo_key', 'plantel', ['id_equipo', 'id_torneo'])
    op.create_index('idx_plantel_equipo', 'plantel', ['id_equipo'], unique=False)
    op.alter_column('plantel', 'fecha_creacion',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('plantel', 'id_plantel',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('persona_rol', sa.Column('creado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('persona_rol', sa.Column('creado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('persona_rol', sa.Column('actualizado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('persona_rol', sa.Column('actualizado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'persona_rol', type_='foreignkey')
    op.create_foreign_key('persona_rol_id_persona_fkey', 'persona_rol', 'persona', ['id_persona'], ['id_persona'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('unq_persona_rol_activo', 'persona_rol', ['id_persona', 'rol'], unique=False, postgresql_where='(fecha_hasta IS NULL)')
    op.create_index('idx_persona_rol_rol', 'persona_rol', ['rol'], unique=False)
    op.create_index('idx_persona_rol_persona', 'persona_rol', ['id_persona'], unique=False)
    op.create_index('idx_persona_rol_activo', 'persona_rol', ['id_persona'], unique=False, postgresql_where='(fecha_hasta IS NULL)')
    op.alter_column('persona_rol', 'rol',
               existing_type=sa.String(length=30),
               type_=postgresql.ENUM('jugador', 'entrenador', 'arbitro', name='rol_persona_tipo'),
               existing_nullable=False)
    op.alter_column('persona_rol', 'id_persona_rol',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('persona', sa.Column('creado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('persona', sa.Column('creado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('persona', sa.Column('actualizado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('persona', sa.Column('actualizado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index('idx_persona_nombre_apellido', 'persona', ['nombre', 'apellido'], unique=False)
    op.create_index('idx_persona_dni', 'persona', ['dni'], unique=False)
    op.alter_column('persona', 'genero',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('Masculino', 'Femenino', name='genero_persona_tipo'),
               existing_nullable=False)
    op.alter_column('persona', 'id_persona',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('partido', sa.Column('id_capitan_visitante', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('partido', sa.Column('confirmado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('partido', sa.Column('creado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('partido', sa.Column('id_capitan_local', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('partido', sa.Column('actualizado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('partido', sa.Column('creado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('partido', sa.Column('actualizado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('partido', sa.Column('confirmado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'partido', type_='foreignkey')
    op.drop_constraint(None, 'partido', type_='foreignkey')
    op.create_foreign_key('partido_id_capitan_visitante_fkey', 'partido', 'plantel_integrante', ['id_capitan_visitante'], ['id_plantel_integrante'])
    op.create_foreign_key('partido_id_capitan_local_fkey', 'partido', 'plantel_integrante', ['id_capitan_local'], ['id_plantel_integrante'])
    op.create_unique_constraint('partido_unq_equipo_fecha_horario', 'partido', ['id_torneo', 'fecha', 'id_local', 'id_visitante'])
    op.create_index('idx_partido_visitante', 'partido', ['id_visitante'], unique=False)
    op.create_index('idx_partido_torneo_fecha', 'partido', ['id_torneo', 'fecha'], unique=False)
    op.create_index('idx_partido_local', 'partido', ['id_local'], unique=False)
    op.create_index('idx_partido_fecha_horario', 'partido', ['fecha', 'horario'], unique=False)
    op.create_index('idx_creado_por_partido', 'partido', ['creado_por'], unique=False)
    op.create_index('idx_creado_en_partido', 'partido', ['creado_en'], unique=False)
    op.create_index('idx_confirmado_en_partido', 'partido', ['confirmado_en'], unique=False)
    op.create_index('idx_actualizado_en_partido', 'partido', ['actualizado_en'], unique=False)
    op.alter_column('partido', 'tipo_fase',
               existing_type=sa.String(),
               type_=postgresql.ENUM('liga', 'eliminacion', 'grupos', name='tipo_fase_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'liga'::tipo_fase_enum"))
    op.alter_column('partido', 'horario',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('partido', 'id_partido',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('partido', 'capitan_visitante')
    op.drop_column('partido', 'capitan_local')
    op.add_column('participan_partido', sa.Column('actualizado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('participan_partido', sa.Column('creado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('participan_partido', sa.Column('id_plantel_integrante', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('participan_partido', sa.Column('creado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('participan_partido', sa.Column('actualizado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'participan_partido', type_='foreignkey')
    op.create_foreign_key('participan_partido_id_plantel_integrante_fkey', 'participan_partido', 'plantel_integrante', ['id_plantel_integrante'], ['id_plantel_integrante'], ondelete='CASCADE')
    op.create_unique_constraint('unq_jugador_partido', 'participan_partido', ['id_partido', 'id_plantel_integrante'])
    op.create_index('idx_participante_integrante', 'participan_partido', ['id_plantel_integrante'], unique=False)
    op.create_index('idx_participacion_partido', 'participan_partido', ['id_partido'], unique=False)
    op.alter_column('participan_partido', 'numero_camiseta',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('participan_partido', 'id_participante_partido',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('participan_partido', 'id_plantel')
    op.add_column('gol', sa.Column('anulado', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('gol', sa.Column('actualizado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('gol', sa.Column('anulado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('gol', sa.Column('creado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('gol', sa.Column('anulado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('gol', sa.Column('motivo_anulacion', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('gol', sa.Column('creado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('gol', sa.Column('actualizado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'gol', type_='foreignkey')
    op.drop_constraint(None, 'gol', type_='foreignkey')
    op.create_foreign_key('gol_id_participante_partido_fkey', 'gol', 'participan_partido', ['id_participante_partido'], ['id_participante_partido'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('gol_id_partido_fkey', 'gol', 'partido', ['id_partido'], ['id_partido'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('idx_gol_partido', 'gol', ['id_partido'], unique=False)
    op.create_index('idx_gol_jugador', 'gol', ['id_participante_partido', 'anulado'], unique=False)
    op.alter_column('gol', 'referencia_gol',
               existing_type=sa.String(),
               type_=postgresql.ENUM('GJ', 'GC', 'GP', 'DP', name='referencia_gol_enum'),
               existing_nullable=True)
    op.alter_column('gol', 'id_gol',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('fase', sa.Column('actualizado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('fase', sa.Column('id_torneo', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('fase', sa.Column('creado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('fase', sa.Column('creado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('fase', sa.Column('actualizado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'fase', type_='foreignkey')
    op.create_foreign_key('fase_id_torneo_fkey', 'fase', 'torneo', ['id_torneo'], ['id_torneo'], ondelete='CASCADE')
    op.alter_column('fase', 'tipo',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('liga', 'eliminacion', 'grupos', name='tipo_fase_enum'),
               existing_nullable=False)
    op.alter_column('fase', 'id_fase',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('fase', 'torneo_id')
    op.drop_constraint(None, 'equipo', type_='foreignkey')
    op.create_foreign_key('equipo_id_club_fkey', 'equipo', 'club', ['id_club'], ['id_club'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_index('idx_equipo_club', 'equipo', ['id_club'], unique=False)
    op.create_unique_constraint('equipo_unq_club_categoria', 'equipo', ['id_club', 'nombre', 'categoria'])
    op.alter_column('equipo', 'actualizado_en',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('equipo', 'creado_en',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('equipo', 'id_equipo',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('club', sa.Column('creado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('club', sa.Column('creado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('club', sa.Column('actualizado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('club', sa.Column('actualizado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint('club_unq_nombre_ciudad', 'club', ['nombre', 'ciudad'])
    op.alter_column('club', 'ciudad',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('club', 'provincia',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('club', 'id_club',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('fixture_partido',
    sa.Column('id_fixture_partido', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('id_fixture_fecha', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_equipo_local', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_equipo_visitante', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jugado', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('id_partido_real', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('creado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.CheckConstraint('id_equipo_local <> id_equipo_visitante', name='chk_fixture_equipos_distintos'),
    sa.ForeignKeyConstraint(['id_equipo_local'], ['equipo.id_equipo'], name='fixture_partido_id_equipo_local_fkey'),
    sa.ForeignKeyConstraint(['id_equipo_visitante'], ['equipo.id_equipo'], name='fixture_partido_id_equipo_visitante_fkey'),
    sa.ForeignKeyConstraint(['id_fixture_fecha'], ['fixture_fecha.id_fixture_fecha'], name='fixture_partido_id_fixture_fecha_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_partido_real'], ['partido.id_partido'], name='fixture_partido_id_partido_real_fkey'),
    sa.PrimaryKeyConstraint('id_fixture_partido', name='fixture_partido_pkey'),
    sa.UniqueConstraint('id_fixture_fecha', 'id_equipo_local', 'id_equipo_visitante', name='unq_fixture_partido')
    )
    op.create_table('auditoria_log',
    sa.Column('id_log', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('tabla_afectada', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('id_registro', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('operacion', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('valores_anteriores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('valores_nuevos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('usuario', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('fecha_hora', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint("operacion::text = ANY (ARRAY['INSERT'::character varying, 'UPDATE'::character varying, 'DELETE'::character varying]::text[])", name='auditoria_log_operacion_check'),
    sa.PrimaryKeyConstraint('id_log', name='auditoria_log_pkey')
    )
    op.create_index('idx_auditoria_usuario', 'auditoria_log', ['usuario', 'fecha_hora'], unique=False)
    op.create_index('idx_auditoria_tabla_fecha', 'auditoria_log', ['tabla_afectada', 'fecha_hora'], unique=False)
    op.create_index('idx_auditoria_operacion', 'auditoria_log', ['operacion', 'fecha_hora'], unique=False)
    op.create_table('fixture_fecha',
    sa.Column('id_fixture_fecha', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('id_torneo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('numero_fecha', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rueda', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('fecha_programada', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('creado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('creado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_torneo'], ['torneo.id_torneo'], name='fixture_fecha_id_torneo_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_fixture_fecha', name='fixture_fecha_pkey'),
    sa.UniqueConstraint('id_torneo', 'numero_fecha', name='unq_fixture_fecha')
    )
    op.create_table('inscripcion_torneo',
    sa.Column('id_inscripcion', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('id_equipo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_torneo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genero', postgresql.ENUM('Masculino', 'Femenino', 'Mixto', name='genero_competencia_tipo'), autoincrement=False, nullable=False),
    sa.Column('fecha_inscripcion', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=True),
    sa.Column('creado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('actualizado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('creado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('actualizado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_equipo'], ['equipo.id_equipo'], name='inscripcion_torneo_id_equipo_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_torneo'], ['torneo.id_torneo'], name='inscripcion_torneo_id_torneo_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_inscripcion', name='inscripcion_torneo_pkey'),
    sa.UniqueConstraint('id_equipo', 'id_torneo', name='inscripcion_equipo_torneo_unq')
    )
    op.create_index('idx_inscripcion_torneo', 'inscripcion_torneo', ['id_torneo'], unique=False)
    op.create_index('idx_inscripcion_equipo', 'inscripcion_torneo', ['id_equipo'], unique=False)
    op.create_table('permiso_user_tabla',
    sa.Column('id_permiso', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('rol_usuario', postgresql.ENUM('superusuario', 'admin', 'editor', 'lector', name='usuario_tipo'), autoincrement=False, nullable=False),
    sa.Column('tabla', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('operacion', postgresql.ENUM('select', 'insert', 'update', 'delete', name='operacion_permiso_tipo'), autoincrement=False, nullable=False),
    sa.Column('permitido', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('creado_en', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('creado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_permiso', name='permiso_user_tabla_pkey'),
    sa.UniqueConstraint('rol_usuario', 'tabla', 'operacion', name='unq_permiso')
    )
    # ### end Alembic commands ###
